"""Tool definitions and file operations for Amarillo."""

from .tools import (
    get_function_schemas,
    get_tools_schema,
    ToolExecutor,
    parse_tool_call_arguments,
    build_tool_call_message,
    build_legacy_function_call_message,
)
from .file_tools import (
    read_file,
    read_file_range,
    list_dir,
    glob_search,
    search_in_file,
    apply_patch,
    apply_patch_multiple,
    write_file,
    insert_at_line,
    delete_lines,
    get_file_tool_schemas,
    get_file_tools_schema,
    execute_file_tool,
    is_file_tool,
    get_token_budget,
    reset_token_budget,
    estimate_tokens,
    FileChunk,
    TokenBudget,
    FILE_TOOL_NAMES,
)

__all__ = [
    # Tool Definitions
    "get_function_schemas",
    "get_tools_schema",
    "ToolExecutor",
    "parse_tool_call_arguments",
    "build_tool_call_message",
    "build_legacy_function_call_message",
    # File Tools
    "read_file",
    "read_file_range",
    "list_dir",
    "glob_search",
    "search_in_file",
    "apply_patch",
    "apply_patch_multiple",
    "write_file",
    "insert_at_line",
    "delete_lines",
    "get_file_tool_schemas",
    "get_file_tools_schema",
    "execute_file_tool",
    "is_file_tool",
    "get_token_budget",
    "reset_token_budget",
    "estimate_tokens",
    "FileChunk",
    "TokenBudget",
    "FILE_TOOL_NAMES",
]
